# Generated by Django 3.2.9 on 2021-12-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Arts',
            new_name='Art',
        ),
    ]
