# Generated by Django 3.1.5 on 2021-12-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_auto_20211222_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='virgo',
            name='map_link',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
