# Generated by Django 3.1.5 on 2021-12-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0008_auto_20211222_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
